loverelay/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

#from django.conf import settings
#from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('lr.urls', namespace='lr')),
]
#] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

lr/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'lr'
urlpatterns = [
    
    url(r'^$', views.index, name='index'),
    url(r'^donation/$', views.donation, name='donation'),
    url(r'^request/$', views.request, name='request'),
    url(r'^loan/$', views.loan, name='loan'),
    url(r'^money/$', views.money, name='moneys'),
    url(r'^refund/(?P<money_id>\d+)/$', views.refund, name='refund'),
    url(r'^moneylist/$', views.moneylist, name='moneylist'),
    url(r'^moneytrack/(?P<money_id>\d+)/$', views.moneytrack, name='moneytrack'),
    url(r'^new_money/$', views.new_money, name='new_money'),
    url(r'^edit_money/(?P<money_id>\d+)/$', views.edit_money, name='edit_money'),
    url(r'^delete_money/(?P<money_id>\d+)/$', views.delete_money, name='delete_money'),
    url(r'^search_money/$', views.search_money, name='search_money'),
    url(r'^search_money_result/(?P<money_id>\d+)/$', views.search_money_result, name='search_money_result'),
    url(r'^makegraph/(?P<money_id>\d+)/(?P<rand>\d+)/', views.makegraph, name='makegraph'),
    url(r'^makebar/$', views.makebar, name='makebar'),
    url(r'^query/(?P<money_id>\d+)/$', views.query, name='query'),
    url(r'^getwordslibs/$', views.getwordslibs, name='getwordslibs'),
    url(r'^getwordslib/(?P<lib_id>\d+)/$', views.getwordslib, name='getwordslib'),
    url(r'^getword/(?P<word>\w+)/$', views.getword, name='getword'),
    url(r'^test/$', views.test, name='test'),
#    url(r'^track/(?P<money_id>\d+)/(?P<add>\d+)/$', views.track, name='track'),
#    url(r'^t.html', TemplateView.as_view(template_name='lr/t.html'), name='t'),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)




lr/forms.py
from django import forms
from django.db import connection

from django.contrib.auth.models import User
from .models import Money, Moneynode

class MoneyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MoneyForm, self).__init__(*args, **kwargs)
#        self.initial['amount']=888
#        self.initial['moneyinout']=""
#        self.initial['user']=""
#        self.initial['cashtype']=""
#        self.initial['parentmoney']=""
#            if self.initial['moneyinout']==1:
#                self.initial['parentmoney']=""
        
     #set user unchangable
#        try:
        if self.data.get('user') != None:
            self.fields['user'].queryset = User.objects.filter(id=self.data.get('user'))
        else:
            if type(self.initial.get('user')) == int:
                self.fields['user'].queryset = User.objects.filter(id=self.initial.get('user'))
            else:
                self.fields['user'].queryset = User.objects.filter(username=self.initial.get('user'))
#        except:
#            pass

#     #set parentmoney.amount > new amount
#        try:
#            if self.initial['amount'] != None:
#                self.fields['parentmoney'].queryset = Money.objects.filter(amount__gt=self.initial['amount']).order_by('-amount')
#        except:
#            pass
#

    def clean_user(self):
        user = self.cleaned_data['user']
#        if str(user) != 'wanjun':
#            raise forms.ValidationError("Please input correct info.")
        return user

    def clean_parentmoney(self):
        if self.initial.get('id') != None and self.cleaned_data['parentmoney'] != None:    #need to check if recursive reference exists
            cursor = connection.cursor()
            cursor.execute("call ischild(%s, %s, @p1)", (str(self.cleaned_data['parentmoney'].id), str(self.initial.get('id')),))
            cur2 = connection.cursor()
            cur2.execute("select @p1")
            ischild = cur2.fetchone()[0]
            if ischild == 1:
                self._errors["parentmoney"] = ["父记录被循环引用，请选择另一条父记录。"]
        return self.cleaned_data['parentmoney']
            
        # if self.cleaned_data['parentmoney'] != None:
            # parentmoney = self.cleaned_data['parentmoney']
# #        if str(user) != 'wanjun':
# #            raise forms.ValidationError("Please input correct info.")
            # parentmoney0 = Money.objects.get(id=parentmoney.money_id)
            # return parentmoney0
        # else:
            # return None

    def clean(self):
        form_data = self.cleaned_data
#        if form_data['amount'] > form_data['parentmoney'].amount:
        if form_data['parentmoney'] != None and form_data['amount'] > form_data['parentmoney'].amount:
            self._errors["amount"] = ["请输入低于父记录的金额。"]
            del form_data['amount']
        return form_data
                
    class Meta:
        model = Money
        fields = ['id', 'amount', 'purpose', 'user', 'cashtype', 'beneficiarydesignated', 'parentmoney']
        labels = {'amount' : '金额', 'purpose': '类别', 'user': '用户', 'cashtype': '币种', 'beneficiarydesignated': '指定受益人', 'parentmoney': '父记录'}

class RequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        if self.data.get('user') != None:
            self.fields['user'].queryset = User.objects.filter(id=self.data.get('user'))
        else:
            if type(self.initial.get('user')) == int:
                self.fields['user'].queryset = User.objects.filter(id=self.initial.get('user'))
            else:
                self.fields['user'].queryset = User.objects.filter(username=self.initial.get('user'))
        self.fields['parentmoney'].queryset = Money.objects.filter(purpose=1).order_by('-amount')

    def clean(self):
        form_data = self.cleaned_data
        if form_data['parentmoney'] != None and form_data['amount'] > form_data['parentmoney'].amount:
            self._errors["amount"] = ["请输入低于父记录的金额。"]
            del form_data['amount']
        return form_data
                
    class Meta:
        model = Money
        fields = ['amount', 'purpose', 'user', 'cashtype', 'donatordesignated', 'parentmoney']
        labels = {'amount' : '金额', 'purpose': '类别', 'user': '用户', 'cashtype': '币种', 'donatordesignated': '指定捐赠人', 'parentmoney': '父记录'}

class MoneydetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MoneydetailForm, self).__init__(*args, **kwargs)
#        self.initial['amount']=888
#        self.initial['moneyinout']=""
#        self.initial['user']=""
#        self.initial['cashtype']=""
#        self.initial['parentmoney']=""
        try:
#            if self.initial['moneyinout']==1:
#                self.initial['parentmoney']=""
            if self.initial['amount'] != None:
                self.fields['parentmoney'].queryset = Money.objects.filter(amount__gt=self.initial['amount']).order_by('-amount')
        except:
            pass
            
    class Meta:
        model = Money
        fields = '__all__'
        labels = {'id': 'ID', 'amount': '金额', 'purpose': '类别', 'user': '用户', 'cashtype': '币种', 'parentmoney': '父记录', 'test': 'Test'}

class MoneylistForm(forms.Form):
    amount = forms.IntegerField()
    purpose = forms.IntegerField()
    user = forms.CharField()
    cashtype = forms.IntegerField()
    parentmoney = forms.IntegerField()
    

lr/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
import json
from django.core import serializers
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db import connection
import hashlib
from lxml import etree
from django.utils.encoding import smart_str
#below line shoud be removed after test
from django.views.decorators.csrf import csrf_exempt
from wechat_sdk import WechatBasic
from wechat_sdk.exceptions import ParseError
from wechat_sdk.messages import TextMessage

import numpy as np
import matplotlib
matplotlib.use('Agg')    #without this line not possible to draw a picture in linux
import matplotlib.pyplot as plt
#plt.rcParams['font.sas-serif']=['simhei'] #用来正常显示中文标签
#plt.rcParams['axes.unicode_minus']=False #用来正常显示负号

from pylab import *  
#mpl.rcParams['font.sans-serif'] = ['SimHei'] 

from io import BytesIO
import pygal
import random
import base64        #used to encode plt picture data to base64 and transfer them to template

from .models import Money, Cashtype, Moneynode, Wechatreplymsg
from django.contrib.auth.models import User
#from django.forms import inlineformset_factory
from .forms import MoneyForm, RequestForm, MoneydetailForm, MoneylistForm

# Create your views here.
@csrf_exempt
def index(request):
    WECHAT_TOKEN = 'myweixinpassword'
    AppID = 'wx3370960315272e32'
    AppSecret = 'e6d6b879a09b13d5b19f8fda241adc6c'
    MAX_REPLY_LENGTH = 630    #每次回复的文本最大长度
    # 实例化 WechatBasic
    wechat_instance = WechatBasic(
        token=WECHAT_TOKEN,
        appid=AppID,
        appsecret=AppSecret
    )   
    
    if request.method == 'GET':
        try:
            signature = request.GET.get('signature', None)
        except:
            pass
        if signature == None:           #正常的L访问
            return render(request, 'lr/index.html')
        # 下面是微信公众号发来的验证本机的消息    
        # 检验合法性
        # 从 request 中提取基本信息 (signature, timestamp, nonce, xml)
        signature = request.GET.get('signature')
        timestamp = request.GET.get('timestamp')
        nonce = request.GET.get('nonce')
        if not wechat_instance.check_signature(signature=signature, timestamp=timestamp, nonce=nonce):
            return HttpResponseBadRequest('Verify Failed')
        return HttpResponse(request.GET.get('echostr', ''), content_type="text/plain")
    # 解析本次请求的 XML 数据
    try:
        wechat_instance.parse_data(data=request.body)
    except ParseError:
        return HttpResponseBadRequest('Invalid XML Data')
    # 获取解析好的微信请求信息
    message = wechat_instance.get_message()
    # 关注事件以及不匹配时的默认回复
    if isinstance(message, TextMessage):
        # 当前会话内容
        content = message.content.strip()
        if content == "news":
            response = wechat_instance.response_news([
                {
                    'title': u'新闻标题',
                    'description': u'新闻描述',
                    'picurl': u"https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=1187077172,2563639533&amp;fm=200&amp;gp=0.jpg",
                    'url': u'http://www.baidu.com/',
                }
            ])

        elif content.endswith("新闻"):
            response = wechat_instance.response_text(content='去看看头条新闻吧，https://www.toutiao.com/ch/news_hot/')

        elif content.endswith("图片"):
            urls = []
            rooturl = 'http://www.ivsky.com/tupian'
            keywords = [content.strip('图片')]
            #if no keywords input then give random keywords
            if not content.strip('图片'):
                keywords = [random.choice(['动物', '风光', '花卉', '海洋', '城市', '节日', '艺术'])]
            urls = get_urls_by_keywords(rooturl, keywords)
            if not urls:
                reply_text = "没找到你要的图片，过一会儿再说吧？/::)"
                response = wechat_instance.response_text(content=reply_text)
            else:
                #find contents from urls
                contents = []
                contents = get_contents_from_urls(urls)
                if not contents:
                    reply_text = "没找到你要的图片，过一会儿再说吧？/::)"
                    response = wechat_instance.response_text(content=reply_text)
                else:
                    picture = random.choice(contents)
                    response = wechat_instance.response_news([
                        {
                            'title': picture['title'],
                            'picurl': picture['picurl'],
                        }
                    ])
            
        elif content == "笑话":
            reply_text = ""        
            rooturl = 'http://xiaohua.zol.com.cn/new/' + str(random.choice(range(2,5000))) + '.html'
            urls = [rooturl]
            #find contents from urls
            contents = []
            contents = get_contents_from_urls(urls)
            if not contents:
                reply_text = "没找到你要的笑话，过一会儿再说吧？/::)"
                response = wechat_instance.response_text(content=reply_text)
            else:
                #从列表里面随机挑一个，把网址发给函数取正文
                url = random.choice(contents)['url']
                joke = get_detail_from_url(url)
                if len(joke) > MAX_REPLY_LENGTH:
                    reply_text = joke[0:MAX_REPLY_LENGTH] + "..." + "\n\n" + "【内容太长，没有完全显示，点这里看全文：" + url + "】"
                else:
                    reply_text = joke
                if not reply_text:
                    reply_text = "没找到你要的笑话，过一会儿再说吧？/::)"
                response = wechat_instance.response_text(content=reply_text)

        elif content == "天气":
            import urllib.request
#            from bs4 import BeautifulSoup
            from lxml import etree
            url = 'http://www.weather.com.cn/weather/101200101.shtml'
            headers = {'User-Agent':'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0'}
            req=urllib.request.Request(url=url,headers=headers)
            resp = urllib.request.urlopen(req)
            html = resp.read()
            selector = etree.HTML(html)
            day1_date = selector.xpath('//*[@id="7d"]/ul/li[1]/h1/text()')[0]
            day1_weather = selector.xpath('//*[@id="7d"]/ul/li[1]/p[1]/text()')[0]
            if selector.xpath('//*[@id="7d"]/ul/li[1]/p[2]/span/text()'):  
                day1_temp_h = selector.xpath('//*[@id="7d"]/ul/li[1]/p[2]/span/text()')[0] + '/'
            else:
                day1_temp_h = ""
            day1_temp_l = selector.xpath('//*[@id="7d"]/ul/li[1]/p[2]/i/text()')[0]
            day1_wind = selector.xpath('//*[@id="7d"]/ul/li[1]/p[3]/i/text()')[0]
            day1_text = day1_date + day1_weather + ", " + day1_temp_h + day1_temp_l + ", 风力" + day1_wind

            day2_date = selector.xpath('//*[@id="7d"]/ul/li[2]/h1/text()')[0]
            day2_weather = selector.xpath('//*[@id="7d"]/ul/li[2]/p[1]/text()')[0]
            day2_temp_h = selector.xpath('//*[@id="7d"]/ul/li[2]/p[2]/span/text()')[0]
            day2_temp_l = selector.xpath('//*[@id="7d"]/ul/li[2]/p[2]/i/text()')[0]
            day2_wind = selector.xpath('//*[@id="7d"]/ul/li[2]/p[3]/i/text()')[0]
            day2_text = day2_date + day2_weather + ", " + day2_temp_h + "/" + day2_temp_l + ", 风力" + day2_wind

            day3_date = selector.xpath('//*[@id="7d"]/ul/li[3]/h1/text()')[0]
            day3_weather = selector.xpath('//*[@id="7d"]/ul/li[3]/p[1]/text()')[0]
            day3_temp_h = selector.xpath('//*[@id="7d"]/ul/li[3]/p[2]/span/text()')[0]
            day3_temp_l = selector.xpath('//*[@id="7d"]/ul/li[3]/p[2]/i/text()')[0]
            day3_wind = selector.xpath('//*[@id="7d"]/ul/li[3]/p[3]/i/text()')[0]
            day3_text = day3_date + day3_weather + ", " + day3_temp_h + "/" + day3_temp_l + ", 风力" + day3_wind

            day4_date = selector.xpath('//*[@id="7d"]/ul/li[4]/h1/text()')[0]
            day4_weather = selector.xpath('//*[@id="7d"]/ul/li[4]/p[1]/text()')[0]
            day4_temp_h = selector.xpath('//*[@id="7d"]/ul/li[4]/p[2]/span/text()')[0]
            day4_temp_l = selector.xpath('//*[@id="7d"]/ul/li[4]/p[2]/i/text()')[0]
            day4_wind = selector.xpath('//*[@id="7d"]/ul/li[4]/p[3]/i/text()')[0]
            day4_text = day4_date + day4_weather + ", " + day4_temp_h + "/" + day4_temp_l + ", 风力" + day4_wind

            reply_text = day1_text + '\n' + day2_text + '\n' + day3_text + '\n' + day4_text + '\n'
            response = wechat_instance.response_text(content=reply_text)
            
        elif content == "故事":
            reply_text = ""        
            rooturl = 'https://www.jianshu.com'
            keywords = [
                '故事',
            ]

            urls = get_urls_by_keywords(rooturl, keywords)


        ##################################################################

#            if len(urls):
#                reply_text = urls[1]
#            else:
#                reply_text = "没找到你要的故事，过一会儿再说吧？/::)"
#            reply_text = len(urls)
#            response = wechat_instance.response_text(content=reply_text)
#            return HttpResponse(response, content_type="application/xml")

        ##################################################################






            if not urls:
                reply_text = "没找到你要的故事，过一会儿再说吧？/::)"
                response = wechat_instance.response_text(content=reply_text)
            else:
                #find contents from urls
                contents = []
                contents = get_contents_from_urls(urls)
                if not contents:
                    reply_text = "没找到你要的故事，过一会儿再说吧？/::)"
                    response = wechat_instance.response_text(content=reply_text)
                else:
                    #从列表里面随机挑一个，把网址发给函数取正文

lr/templates/lr/delete_money.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-home" style="color:#aaaaaa;"></span>首页</button></a>
    <a href="{% url 'lr:donation' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-heart" style="color:#aaaaaa;"></span>捐赠</button></a>
    <a href="{% url 'lr:request' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-envelope" style="color:#aaaaaa;"></span>求助</button></a>
    <a href="{% url 'lr:moneys' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#f79646; color:#000000; border-style: none; outline: none;"><span class="glyphicon glyphicon-tree-deciduous" style="color:#ff0000;"></span>爱心树</button></a>
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-info-sign" style="color:#aaaaaa;"></span>本站说明</button></a>
{% endblock header %}



{% block content %}
    <script>

        window.addEventListener("load", function(){
            var obj = document.getElementById("myform")["id_moneyinout"];
            obj.addEventListener("change", function(){
                set_parentmoney();
                }, false);
            obj = null;
            }, false);
            
        function set_parentmoney(){
            if (document.getElementById("myform")["id_moneyinout"].selectedIndex == 0){
                document.getElementById("myform")["id_parentmoney"].selectedIndex = 0;
            };
        }
        
        function is_parentmoney (money_id){
            var XHR = new XMLHttpRequest();
            var v1 = moneyid;
            url = '/search_money_result/' + v1
            XHR.open('GET', url, false);
            XHR.send(null);
            document.getElementById("p1").innerHTML=XHR.responseText;
            
        }
    </script>    

    <div class="container" style="height: 625px;">

        <form id="myform" action="{% url 'lr:delete_money' money_id %}" class='form' method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            
            {% if money.candelete %}
                {% buttons %}
                    <button name='submit' class="btn btn-primary form-button">删除</button>
                {% endbuttons %}
            {% else %}
                {% buttons %}
                    <button name='submit' disabled='disabled' title='已有关联的记录，不能删除。'  class="btn btn-primary form-button">删除</button>
                {% endbuttons %}
                
            {% endif %}
        </form>

    </div>

{% endblock content %}

lr/templates/lr/loan.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h4>Initiate a loan</h4>
{% endblock header %}

{% block content %}
    
    <form action="{% url 'lr:loan' %}" class='form' method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name='submit'>send loan</button>
        {% endbuttons %}
    </form>
{% endblock content %}

lr/templates/lr/moneylist.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Money</h2>
    <a href="{% url 'lr:new_money' %}" style="display:block;text-align: right;">Add money</a>
    
{% endblock header %}

{% block content %}

<form method="post" action="">
    <table>
        {{ formset }}
    </table>
</form>



{% endblock content %}





lr/templates/lr/moneys.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    {% load static %}
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-home" style="color:#aaaaaa;"></span>首页</button></a>
    <a href="{% url 'lr:donation' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-heart" style="color:#aaaaaa;"></span>捐赠</button></a>
    <a href="{% url 'lr:request' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-envelope" style="color:#aaaaaa;"></span>求助</button></a>
    <a href="{% url 'lr:moneys' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#f79646; color:#000000; border-style: none; outline: none;"><span class="glyphicon glyphicon-tree-deciduous" style="color:#ff0000;"></span>爱心树</button></a>
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-info-sign" style="color:#aaaaaa;"></span>本站说明</button></a>
{% endblock header %}

{% block content %}

    <script>

        window.addEventListener("load", function(){
            var obj = document.getElementById("showpicbutton");
            obj.addEventListener("click", function(){
                showpic();
                }, false);
            obj = null;
            }, false);
          
        function showpic(){
            var img = document.getElementById("trackimage");
            var button = document.getElementById("showpicbutton");
            if (img.style.display=='none'){
                img.style.display='block';
                button.innerHTML='隐藏图片';}
            else {
                img.style.display='none';
                button.innerHTML='显示图片';}
            };
          
    </script>    
    
    <div class="container" style="height: 625px;">

        {% if not moneys|length_is:"0" %}
            <table class="table table-bordered table-hover table-condensed table-responsive">
                    <td width=50 align=right><b>ID</b></td>
                    <td width=100 align=right><b>金额</b></td>
                    <td width=100 align=right><b>用户</b></td>
                    <td width=60 align=right><b>币种</b></td>
                    <td width=60 align=right><b>类别</b></td>
                    <td width=30 align=right><b>修改</b></td>
                    <td width=30 align=right><b>删除</b></td>
                    <td width=30 align=right><b>子记录</b></td>
                    <td width=30 align=right><b>父记录</b></td>
                    <td width=30 align=right><b>回赠</b></td>
                {% for money in moneys %}
                    <tr>
                        {% if forloop.first %}      
                            <td width=50 align=right id="money_id"><h5>{{ money.id }}</h5></td>
                        {% else %}
                            <td width=50 align=right><h5>{{ money.id }}</h5></td>
                        {% endif %}
                        <td width=100 align=right><h5>{{ money.amount }}</h5></td>
                        <td width=100 align=right><h5>{{ money.user }}</h5></td>
                        <td width=60 align=right><h5>{{ money.cashtype }}</h5></td>
                        {% ifequal money.purpose_id 4 %}
                            <td width=60 align=right><h5 style="color:red ">{{ money.purpose }}</h5></td>
                        {% else %}
                            <td width=60 align=right><h5>{{ money.purpose }}</h5></td>
                        {% endifequal %}
                        <td width=30 align=right><h5><a href="{% url 'lr:edit_money' money.id %}">修改</a></h5></td>
                        {% if money.candelete %}
                            <td width=30 align=right><h5><a href="{% url 'lr:delete_money' money.id %}">删除</a></h5></td>
                        {% else %}
                            <td width=30 align=right><h5><a href="" disabled='disabled' title='已有关联的记录，不能删除。'>------</a></h5></td>
                        {% endif %}

                        {% if money.haschild %}
                            <td width=30 align=right><h5><a href="{% url 'lr:moneytrack' money.id %}"><span class="badge" style="background-color:green">子记录</span></a></h5></td>
                        {% else %}
                            <td width=30 align=right><h5><a href="" disabled='disabled' title='No child.'>------</a></h5></td>
                        {% endif %}


                        {% if money.hasparent %}
                            <td width=30 align=right><h5><a href="{% url 'lr:moneytrack' money.parentmoney_id %}">父记录</a></h5></td>
                        {% else %}
                            <td width=30 align=right><h5><a href="{% url 'lr:moneys'%}" title='显示最开始的记录(根记录)。.'>根记录</a></h5></td>
                        {% endif %}

                        {% if money.canrefund %}
                            <td width=30 align=right><h5><a href="{% url 'lr:refund' money.id %}">回赠</a></h5></td>
                        {% else %}
                            <td width=30 align=right><h5><a href="" disabled='disabled' title='Not necessary to refund.'>------</a></h5></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
            {% buttons %}
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object img-responsive" src="data:image/png;base64,{{ picture_data }}" id="trackimage" alt="..."></img>
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">爱心传递</h4>
                        <div>这是初始捐赠记录，点列表中的 <small><span class="badge">子记录</span></small> 能看到爱心传递路线。</div>
                    </div>
                    <button name='submit' id="showpicbutton" class="btn btn-info btn-sm">隐藏图片</button>
                </div>
            {% endbuttons %}
        {% else %}
            <h2><span class="label label-default">暂时还没有捐赠记录。</span></h2>
        {% endif %}
        
    </div>
       
{% endblock content %}

lr/templates/lr/new_money.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add money:</h2>
{% endblock header %}

{% block content %}
    
    <form action="{% url 'lr:new_money' %}" class='form' method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name='submit'>add money</button>
        {% endbuttons %}
    </form>
{% endblock content %}

lr/templates/lr/showmsg.html
{% extends 'lr/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Information</h2>
{% endblock header %}



{% block content %}

    <h3>{{ msg }}</h3>

{% endblock content %}