loverelay/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

#from django.conf import settings
#from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('lr.urls', namespace='lr')),
]
#] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

lr/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'lr'
urlpatterns = [
    
    url(r'^$', views.index, name='index'),
    url(r'^donation/$', views.donation, name='donation'),
    url(r'^request/$', views.request, name='request'),
    url(r'^loan/$', views.loan, name='loan'),
    url(r'^money/$', views.money, name='moneys'),
    url(r'^refund/(?P<money_id>\d+)/$', views.refund, name='refund'),
    url(r'^moneylist/$', views.moneylist, name='moneylist'),
    url(r'^moneytrack/(?P<money_id>\d+)/$', views.moneytrack, name='moneytrack'),
    url(r'^new_money/$', views.new_money, name='new_money'),
    url(r'^edit_money/(?P<money_id>\d+)/$', views.edit_money, name='edit_money'),
    url(r'^delete_money/(?P<money_id>\d+)/$', views.delete_money, name='delete_money'),
    url(r'^search_money/$', views.search_money, name='search_money'),
    url(r'^search_money_result/(?P<money_id>\d+)/$', views.search_money_result, name='search_money_result'),
    url(r'^makegraph/(?P<money_id>\d+)/(?P<rand>\d+)/', views.makegraph, name='makegraph'),
    url(r'^makebar/$', views.makebar, name='makebar'),
    url(r'^query/(?P<money_id>\d+)/$', views.query, name='query'),
    url(r'^getwordslibs/$', views.getwordslibs, name='getwordslibs'),
    url(r'^getwordslib/(?P<lib_id>\d+)/$', views.getwordslib, name='getwordslib'),
    url(r'^getword/(?P<word>\w+)/$', views.getword, name='getword'),
    url(r'^test/$', views.test, name='test'),
#    url(r'^track/(?P<money_id>\d+)/(?P<add>\d+)/$', views.track, name='track'),
#    url(r'^t.html', TemplateView.as_view(template_name='lr/t.html'), name='t'),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)




users/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),

] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)




users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    #logout user
    logout(request)
    return HttpResponseRedirect(reverse('lr:index'))
    
def register(request):
    #register a new user
    if request.method != 'POST':
        #show empty form
        form = UserCreationForm()
    else:
        #deal with filled form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('lr:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends "lr/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#f79646; color:#000000; border-style: none; outline: none;"><span class="glyphicon glyphicon-home" style="color:#ff0000;"></span>首页</button></a>
    <a href="{% url 'lr:donation' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-heart" style="color:#aaaaaa;"></span>捐赠</button></a>
    <a href="{% url 'lr:request' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-envelope" style="color:#aaaaaa;"></span>求助</button></a>
    <a href="{% url 'lr:moneys' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-tree-deciduous" style="color:#aaaaaa;"></span>爱心树</button></a>
    <a href="{% url 'lr:index' %}" style="position:relative; top: 5px"><button type="button" class="btn btn-primary btn-xs" style="background:#337ab7; color:#aaaaaa; border-style: none; outline: none;"><span class="glyphicon glyphicon-info-sign" style="color:#aaaaaa;"></span>本站说明</button></a>
{% endblock header %}

{% block content %}
    
    {% load static %}
    <div class="container" style="height: 625px;">
        <div class="row">
            <div class="col-sm-2">

                <form method="post" action="{% url 'users:login' %}" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                
                {% buttons %}
                <button name="submit" class="btn btn-primary">登录</button>
                {% endbuttons %}
                
                <input type="hidden" name="next" value="{% url 'lr:index' %}" />
                </form>
    
            </div>
        </div>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends "lr/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h4>Register a new account</h4>
{% endblock header %}


{% block content %}
    
    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name="submit">register</button>
            <input type="hidden" name="next" value="{% url 'lr:index' %}" />
        {% endbuttons %}
    </form>
    
{% endblock content %}